version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ihjizely_admin
    ports:
      - "5173:5173"  # Vite dev server port
    networks:
      - ihjizely_admin-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5050/api}
    volumes:
      - .:/app  # Mount current directory for live reload
      - /app/node_modules  # Preserve node_modules in container
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate pseudo-TTY

networks:
  ihjizely_admin-network:
    driver: bridge